// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"git.tashilcar.com/core/tashilcar/data/datasources/databases"
	"git.tashilcar.com/core/tashilcar/data/repositories"
	"git.tashilcar.com/core/tashilcar/domain/usecases"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func DB() *gorm.DB {
	gormDB := provideDB()
	return gormDB
}

func DBDS() databases.DBDataSource {
	gormDB := provideDB()
	dbDataSource := databases.NewDBDataSource(gormDB)
	return dbDataSource
}

func GetAPIsInstance() usecases.GetAPIs {
	gormDB := provideDB()
	dbDataSource := databases.NewDBDataSource(gormDB)
	tashilcarRepository := repositories.NewTashilcarRepository(dbDataSource)
	getAPIs := usecases.NewGetAPIs(tashilcarRepository)
	return getAPIs
}

func CreateAPIInstance() usecases.CreateAPI {
	gormDB := provideDB()
	dbDataSource := databases.NewDBDataSource(gormDB)
	tashilcarRepository := repositories.NewTashilcarRepository(dbDataSource)
	createAPI := usecases.NewCreateAPI(tashilcarRepository)
	return createAPI
}

func DeleteAPIInstance() usecases.DeleteAPI {
	gormDB := provideDB()
	dbDataSource := databases.NewDBDataSource(gormDB)
	tashilcarRepository := repositories.NewTashilcarRepository(dbDataSource)
	deleteAPI := usecases.NewDeleteAPI(tashilcarRepository)
	return deleteAPI
}

func EnableCheckHealthInstance() usecases.EnableCheckHealth {
	gormDB := provideDB()
	dbDataSource := databases.NewDBDataSource(gormDB)
	tashilcarRepository := repositories.NewTashilcarRepository(dbDataSource)
	enableCheckHealth := usecases.NewEnableCheckHealth(tashilcarRepository)
	return enableCheckHealth
}

func UpdateResponseStatusInstance() usecases.UpdateResponseStatus {
	gormDB := provideDB()
	dbDataSource := databases.NewDBDataSource(gormDB)
	tashilcarRepository := repositories.NewTashilcarRepository(dbDataSource)
	updateResponseStatus := usecases.NewUpdateResponseStatus(tashilcarRepository)
	return updateResponseStatus
}

// wire.go:

var (
	//	Third-Party
	db = wire.NewSet(provideDB)

	//  DataSources
	dbDS = wire.NewSet(databases.NewDBDataSource, db)

	// Repositories
	repository = wire.NewSet(repositories.NewTashilcarRepository, dbDS)
)
